# Generated by Django 3.2.3 on 2021-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('type', models.IntegerField(verbose_name='苗类型：1-九价 2-四价')),
                ('province', models.CharField(max_length=255, verbose_name='省')),
                ('city', models.CharField(max_length=255, verbose_name='市')),
                ('district', models.CharField(max_length=255, verbose_name='区')),
                ('address', models.CharField(max_length=500, verbose_name='详细地址，用于展示')),
                ('hosptal', models.CharField(max_length=255, verbose_name='医院')),
                ('starttime', models.DateTimeField(verbose_name='开始预约时间')),
                ('endtime', models.DateTimeField(verbose_name='结束预约时间')),
                ('platform', models.IntegerField(verbose_name='平台：1-知苗易约')),
                ('quantity', models.IntegerField(verbose_name='本次放苗数量')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
