# Generated by Django 3.2.3 on 2021-09-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_fusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miaomodel',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='miaomodel',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='miaomodel',
            name='province',
            field=models.CharField(max_length=255, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='miaomodel',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='本次放苗数量'),
        ),
    ]
